%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Monika\Desktop\extract\our
%    code\popularity\new_cluster.xlsx Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/09/27 12:46:37

%% Import the data
[~, ~, raw] = xlsread('D:\STUDIES_MSBR\Academics\BTProject\Final Project\BTP(ipg2012-mentor)\Code\speech-emotional-based classi\new_cluster.xlsx','Sheet1');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,16]);
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create dataset array
newcluster = dataset;

%% Allocate imported array to column variable names
newcluster.SONG = cellVectors(:,1);
newcluster.SpectralCentroidOverallSt = data(:,1);
newcluster.SpectralRolloffPointOvera = data(:,2);
newcluster.SpectralFluxOverallStanda = data(:,3);
newcluster.CompactnessOverallStandar = data(:,4);
newcluster.SpectralVariabilityOveral = data(:,5);
newcluster.RootMeanSquareOverallStan = data(:,6);
newcluster.FractionOfLowEnergyWindow = data(:,7);
newcluster.ZeroCrossingsOverallStand = data(:,8);
newcluster.StrongestBeatOverallStand = data(:,9);
newcluster.BeatSumOverallStandardDev = data(:,10);
newcluster.StrengthOfStrongestBeatOv = data(:,11);
newcluster.LPCOverallStandardDeviati = data(:,12);
newcluster.MethodofMomentsOverallSta = data(:,13);
newcluster.AreaMethodofMomentsofMFCC = data(:,14);
newcluster.Clusters = cellVectors(:,2);

%% Clear temporary variables
clearvars data raw cellVectors R;
%first
%import
%audio
%excell file
 newcluster = newcluster(:,[1 16 2:15]);
 new_audio=dataset2cell(audio);
 compare_with=newcluster(:,3:16);
 compare_with(1,:) = [];
 


 %mat_input=cell2mat(cell_input);
   cell_compare_with=dataset2cell(compare_with);
   cell_compare_with(1,:)=[];
   mat_compare_with=cell2mat(cell_compare_with);
    x= wavread('kinky_female_says_thats_enough_both_of_you_followe.wav'); 
   y=wavread('aaaaashut_up_and_let_me_think_.wav');
  z=wavread('aaaass_says_you_ve_come_t.wav');
  p=wavread('aaas_ooh_la_lah_reaction.wav');
  q=wavread('aamale_says_enthusiastic_yes_.wav');
  r=wavread('awizard_says_one_must_try.wav');
  t=wavread('english_male_butler_says_good_morning_sir.wav');
  e=wavread('father_christmas_says_ho_ho_merry_xmas_.wav');
  m=wavread('female_news_reader_says_the_stock_market_went_thro.wav');
  n= wavread('female_says_oh_i_m_sorry_.wav');
 
  display('speech1');
   display('speech2');
   display('speech3');
   display('speech4');
   display('speech5');
   display('speech6');
   display('speech7');
   display('speech8');
   display('speech9');
   display('speech10');
   str = input('select from sample speeches: ','s')
   if(strcmp(str,'speech1'))
       wavplay(t,44100);
   elseif(strcmp(str,'speech2'))
       wavplay(e,44100);
   elseif(strcmp(str,'speech3'))
       wavplay(m,44100);
   elseif(strcmp(str,'speech4'))
       wavplay(n,44100);
   elseif(strcmp(str,'speech5'))
       wavplay(x,44100);
   elseif(strcmp(str,'speech6'))
       wavplay(q,44100);
   elseif(strcmp(str,'speech7'))
       wavplay(p,44100);
   elseif(strcmp(str,'speech8'))
       wavplay(z,44100);
   elseif(strcmp(str,'speech9'))
       wavplay(y,44100);
   elseif(strcmp(str,'speech10'))
       wavplay(r,44100);
   
   end
   
   
        test=new_audio(strcmpi(str,new_audio(:,1)),:);
  test1=test(:,3:16);
  matest=cell2mat(test1);
 [ncb,cheb] = knnsearch(matest,mat_compare_with,'k',10,'distance','chebychev');
  cheb_cell=mat2dataset(cheb);
  song_cluster=newcluster(:,1:2);
  song_cluster(1,:) = [];
  related_song=horzcat(song_cluster,cheb_cell);
   new = sortrows(related_song,'cheb1','ascend');
   final_songs_after_knn=new(:,1);
    display( final_songs_after_knn(1:20,:));
    

   
 
    
  
   
   
   
   
   